# Generated by Django 3.0.4 on 2020-03-19 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_hundred_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('first_two_hundred_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('three_hundred_plus_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MeterBoard',
            fields=[
                ('board_name', models.CharField(max_length=200)),
                ('board_number', models.IntegerField(primary_key=True, serialize=False)),
                ('board_owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('board_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerhouse_api.ChargingType')),
            ],
        ),
    ]
