# Generated by Django 3.0.4 on 2020-03-19 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powerhouse_api', '0002_meterreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterBill',
            fields=[
                ('billing_month', models.DateField()),
                ('bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_status', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=6)),
                ('billing_end_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meterbill_ending_reading', to='powerhouse_api.MeterReading')),
                ('billing_meterboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powerhouse_api.MeterBoard')),
                ('billing_start_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meterbill_starting_reading', to='powerhouse_api.MeterReading')),
            ],
        ),
    ]
