# Generated by Django 3.0.4 on 2020-03-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhouse_api', '0003_meterbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingtype',
            name='name_short',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
