# Generated by Django 3.0.4 on 2020-03-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powerhouse_api', '0004_chargingtype_name_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingtype',
            old_name='name_short',
            new_name='name_shortform',
        ),
    ]
