# Generated by Django 3.0.4 on 2020-05-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhouse_api', '0009_chargingtype_first_three_hundred_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='slips'),
        ),
    ]
