# Generated by Django 3.0.4 on 2020-05-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerhouse_api', '0010_payment_payment_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')], default='APPROVED', max_length=8),
        ),
    ]
